<section id="home"></section>
<header class="masthead" style="background-image:url('<?php echo $getPageDataArray['ARTIST_IMAGE']; ?>')">
    <div class="intro-body" style="backdrop-filter: opacity(60%)">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="brand-heading" style="font-size: calc(1em + 4vw);"><?php echo $getPageDataArray['ARTIST_NAME']; ?></h1><br/>
                </div>
            </div>
        </div>
    </div>
</header>