<section id="story" class="content-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 mx-auto">
                <h2>Over de band</h2>
                <?php echo $getPageDataArray['ARTIST_CONTENT_ABOUT']; ?>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 mx-auto mt-5">
                <?php echo $getPageDataArray['ARTIST_CONTENT_HISTORY']; ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 mt-5">
                <?php echo $getPageDataArray['ARTIST_FOLLOW_BUTTON']; ?>
            </div>
        </div>
    </div>
    <section id="discografie" class="content-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 mx-auto">
                    <h2>Discografie</h2>
                    <p>Zie hier de discografie van de studio-albums van <?php echo $getPageDataArray['ARTIST_NAME']; ?>.</p><br>
                    <div class="row">
                        <div class="col-md-12 mx-auto text-center">
                            <div class="row">
                                <br><br>
                                <table class="table table-borderless table-active">
                                    <!--                    This section is for the discography-->
                                    <thead style="color: white;">
                                    <tr>
                                        <th scope="col">Titel</th>
                                        <th scope="col">Jaar van uitkomst</th>
                                        <th scope="col">In collectie</th>
                                        <th scope="col"></th>
                                    </tr>
                                    </thead>
                                    <tbody style="color: white;">
                                    <?php
                                    $i = 0;
                                    while ($showList = $getDiscoData->fetch_array()) {
                                        ?>
                                            <tr>
                                                <td><?php echo $showList['DISCO_ALBUM_TITLE'] ?></td>
                                                <td><?php echo $showList['DISCO_ALBUM_RELEASE_YEAR'] ?></td>
                                                <?php
                                                switch ($showList['DISCO_ALBUM_IS_PRESENT']) {
                                                    case ('Y'):
                                                        ?>
                                                            <td><i class="fa fa-check fa-fw"></i></td>
                                                        <?php
                                                        break;
                                                    case ('N'):
                                                        ?>
                                                            <td><i class="fa fa-times fa-fw"></i></td>
                                                        <?php
                                                        break;
                                                    }
                                                ?>
                                            </tr>
                                        <?php
                                    $i++;
                                    }
                                    ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
    </section>
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-12 mx-auto text-center">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item nav-link js-scroll-trigger" role="presentation"><a class="js-scroll-trigger"
                                                                                           href="#home">
                            <button class="btn btn-primary btn-lg btn-default" type="button"><i
                                    class="fa fa-arrow-up fa-fw"></i><span class="network-name" style="font-size: 70%">&nbsp;Naar boven</span>
                            </button>
                        </a></li>
                </ul>
            </div>
        </div>
    </div>
</section>