<footer>
    <div class="container text-center">
        <p>Copyright © <a href="mailto:info@hetplatenhuis.nl">HetPlatenHuis</a> || 2020</p>
        <small>Favicon gemaakt door <a href="https://www.flaticon.com/authors/iconixar" title="iconixar"
                                       target="_blank">iconixar</a> van <a href="https://www.flaticon.com/"
                                                                           title="Flaticon" target="_blank">
                www.flaticon.com</a></small>
        <small> || Foto's van <a href="https://unsplash.com/images/stock/non-copyrighted" target="_blank">UnSplash</a>
            (no copyright)</small>
    </div>
</footer>