<nav class="navbar navbar-light navbar-expand-md navbar navbar-expand-lg fixed-top" id="mainNav"
     style="backdrop-filter: opacity(30%)">
    <div class="container"><a class="navbar-brand js-scroll-trigger" href="../index.php">HET PLATENHUIS - <?php echo $getPageDataArray['ARTIST_NAME']; ?></a>
        <button data-toggle="collapse" class="navbar-toggler navbar-toggler-right" data-target="#navbarResponsive"
                type="button" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation" value="Menu"><i class="fa fa-bars"></i></button>
        <div class="collapse navbar-collapse text-capitalize" id="navbarResponsive">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item nav-link js-scroll-trigger" role="presentation"><a
                        class="nav-link active js-scroll-trigger" href="../index.php">home</a>
                </li>
                <li class="nav-item nav-link js-scroll-trigger" role="presentation"><a
                        class="nav-link active js-scroll-trigger" href="artiesten.php"><i class="fa fa-reply fa-fw"></i>&nbsp;terug</a></li>
                <li class="nav-item nav-link js-scroll-trigger" role="presentation"><a
                        class="nav-link active js-scroll-trigger" href="#home">top</a></li>
                <li class="nav-item nav-link js-scroll-trigger" role="presentation"><a
                        class="nav-link active js-scroll-trigger" href="#story">story</a></li>
                <li class="nav-item nav-link js-scroll-trigger" role="presentation"><a
                        class="nav-link active js-scroll-trigger" href="#discografie">discografie</a></li>
                <!--                <li class="nav-item nav-link js-scroll-trigger" role="presentation"><a-->
                <!--                        class="nav-link active js-scroll-trigger" href="#timeline">timeline</a></li>-->
            </ul>
        </div>
    </div>
</nav>